openapi: "3.0.0"
info:
  version: 0.1.0
  title: CepteMenu OAS
  description: Open API Specification for Cepte Menu application.
  license:
    name: MIT
  contact:
    name: API Support
    url: https://ceptemenu.app/support
    email: support@ceptemenu.app
servers:
  - url: https://api.ceptemenu.app
tags:
  - name: auth
    description: Authentication related endpoints
  - name: account
    description: Account related endpoints
paths:
  /auth:
    $ref: "./resources/auth.yaml"
  /account:
    $ref: "./resources/account.yaml"
components:
  schemas:
    ValidationError:
      $ref: "./schemas/ValidationError.yaml"
    IssueTokenRequest:
      $ref: "./schemas/IssueTokenRequest.yaml"
    IssueToken:
      $ref: "./schemas/IssueToken.yaml"
  responses:
    UnprocessableContent:
      $ref: "./responses/UnprocessableContent.yaml"
    TokenCreated:
      $ref: "./responses/TokenCreated.yaml"
  securitySchemes:
    bearer:
      type: http
      bearerFormat: JWT
      scheme: bearer
