name: Run linter
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Run Redocly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fluximus-prime/redocly-cli-github-action@v1.0.2
        with:
          args: 'lint'
